name: link_nest
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^10.1.2
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  duration: ^3.0.13
  firebase_core: ^4.1.0
  flash: ^3.1.1
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0-beta.4
  google_fonts: ^6.3.1
  hive_ce_flutter: ^2.3.2
  icons_launcher: ^3.0.2
  internet_connection_checker_plus: ^2.8.0
  intl: ^0.20.2
  multiple_result: ^5.2.0
  path_provider: ^2.1.5
  platform_info: ^5.0.0
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  talker_dio_logger: ^5.0.1
  talker_flutter: ^5.0.1
  talker_riverpod_logger: ^5.0.1
  velocity_x: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.5
  riverpod_test: ^0.1.9
  very_good_analysis: ^9.0.0

  # Added for support WASM
dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/illustrations/
